# Generated by Django 6.0.5 on 2026-06-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeiq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='score_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
