# Generated by Django 6.0.5 on 2026-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeiq', '0002_resumeanalysis_score_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='improved_resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
